# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chainmaker.protos.common import result_pb2 as common_dot_result__pb2
from tee import enclave_outcall_pb2 as tee_dot_enclave__outcall__pb2


class EnclaveOutCallServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OutCallGet = channel.unary_unary(
                '/tee.EnclaveOutCallServer/OutCallGet',
                request_serializer=tee_dot_enclave__outcall__pb2.OutCallGetRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.ContractResult.FromString,
                )
        self.OutCallPut = channel.unary_unary(
                '/tee.EnclaveOutCallServer/OutCallPut',
                request_serializer=tee_dot_enclave__outcall__pb2.OutCallPutRequest.SerializeToString,
                response_deserializer=common_dot_result__pb2.ContractResult.FromString,
                )


class EnclaveOutCallServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OutCallGet(self, request, context):
        """Enclave fetch data from blockchain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OutCallPut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnclaveOutCallServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OutCallGet': grpc.unary_unary_rpc_method_handler(
                    servicer.OutCallGet,
                    request_deserializer=tee_dot_enclave__outcall__pb2.OutCallGetRequest.FromString,
                    response_serializer=common_dot_result__pb2.ContractResult.SerializeToString,
            ),
            'OutCallPut': grpc.unary_unary_rpc_method_handler(
                    servicer.OutCallPut,
                    request_deserializer=tee_dot_enclave__outcall__pb2.OutCallPutRequest.FromString,
                    response_serializer=common_dot_result__pb2.ContractResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tee.EnclaveOutCallServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EnclaveOutCallServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OutCallGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tee.EnclaveOutCallServer/OutCallGet',
            tee_dot_enclave__outcall__pb2.OutCallGetRequest.SerializeToString,
            common_dot_result__pb2.ContractResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OutCallPut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tee.EnclaveOutCallServer/OutCallPut',
            tee_dot_enclave__outcall__pb2.OutCallPutRequest.SerializeToString,
            common_dot_result__pb2.ContractResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
