# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus/dpos/dpos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63onsensus/dpos/dpos.proto\x12\x04\x64pos\"0\n\rCandidateInfo\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\tBK\n\x16org.chainmaker.pb.dposZ1chainmaker.org/chainmaker/pb-go/v2/consensus/dposb\x06proto3')



_CANDIDATEINFO = DESCRIPTOR.message_types_by_name['CandidateInfo']
CandidateInfo = _reflection.GeneratedProtocolMessageType('CandidateInfo', (_message.Message,), {
  'DESCRIPTOR' : _CANDIDATEINFO,
  '__module__' : 'consensus.dpos.dpos_pb2'
  # @@protoc_insertion_point(class_scope:dpos.CandidateInfo)
  })
_sym_db.RegisterMessage(CandidateInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026org.chainmaker.pb.dposZ1chainmaker.org/chainmaker/pb-go/v2/consensus/dpos'
  _CANDIDATEINFO._serialized_start=35
  _CANDIDATEINFO._serialized_end=83
# @@protoc_insertion_point(module_scope)
